export const MPT_ANSWER_SUBMIT = 'MPT_ANSWER_SUBMIT';
export const GAME_TIMER_FINISHED = 'GAME_TIMER_FINISHED';
export const GAME_ALL_QUESTIONS_COMPLETED = 'GAME_ALL_QUESTIONS_COMPLETED';
export const UPDATE_QUESTION_COUNTER = 'UPDATE_QUESTION_COUNTER';
export const NEW_GAME_TICKET_INFO = 'NEW_GAME_TICKET_INFO';
